// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"time"

	"gopkg.in/guregu/null.v4/zero"
)

type MovieDuration struct {
	ID            string      `json:"id"`
	MovieSlug     string      `json:"movie_slug"`
	OwnerID       string      `json:"owner_id"`
	SeasonNumber  zero.Int    `json:"season_number"`
	EpisodeNumber zero.Int    `json:"episode_number"`
	StartAt       zero.Int    `json:"start_at"`
	EndAt         zero.Int    `json:"end_at"`
	AudioLang     zero.String `json:"audio_lang"`
	SubtitleLang  zero.String `json:"subtitle_lang"`
	IpAddress     zero.String `json:"ip_address"`
	UserID        zero.String `json:"user_id"`
	Platform      zero.String `json:"platform"`
	CreatedAt     time.Time   `json:"created_at"`
	Category      string      `json:"category"`
}

type MovieImpression struct {
	ID          string      `json:"id"`
	MovieSlug   string      `json:"movie_slug"`
	OwnerID     string      `json:"owner_id"`
	UserID      zero.String `json:"user_id"`
	IpAddress   zero.String `json:"ip_address"`
	SourcePlace string      `json:"source_place"`
	Country     zero.String `json:"country"`
	Region      zero.String `json:"region"`
	Platform    zero.String `json:"platform"`
	City        zero.String `json:"city"`
	Lon         zero.Float  `json:"lon"`
	Lat         zero.Float  `json:"lat"`
	CreatedAt   time.Time   `json:"created_at"`
	Category    string      `json:"category"`
}

type MovieView struct {
	ID            string      `json:"id"`
	IpAddress     string      `json:"ip_address"`
	UserID        zero.String `json:"user_id"`
	MovieSlug     string      `json:"movie_slug"`
	OwnerID       string      `json:"owner_id"`
	SeasonNumber  zero.Int    `json:"season_number"`
	EpisodeNumber zero.Int    `json:"episode_number"`
	ViewedAt      time.Time   `json:"viewed_at"`
	CreatedAt     time.Time   `json:"created_at"`
	Active        bool        `json:"active"`
	SourcePlace   string      `json:"source_place"`
	AudioLang     zero.String `json:"audio_lang"`
	SubtitleLang  zero.String `json:"subtitle_lang"`
	Country       zero.String `json:"country"`
	Region        zero.String `json:"region"`
	Platform      zero.String `json:"platform"`
	City          zero.String `json:"city"`
	Lon           zero.Float  `json:"lon"`
	Lat           zero.Float  `json:"lat"`
	Category      string      `json:"category"`
}
