// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"context"
)

type Querier interface {
	SelectAllMovies(ctx context.Context) ([]MovieView, error)
}

var _ Querier = (*Queries)(nil)
