project:
  name: &projectName Backend Dev
  gracefulTimeoutSeconds: 5
  version: 1.0.0
  swaggerEnabled: true
  fileUploadMaxMegabytes: 30
  timeout: "10s"
mongodb:
  database: aggregator
logging:
  projectName: *projectName
  code: logrus
  encoding: console
  level: debug
  dateTimeFormat: 2006-01-02 15:04:05
  dateFormat: 2006-01-02
  enableCaller: false
  devMode: true
http:
  host: localhost
  port: 8080
jwt:
  accessTokenTTLMinutes: 30m
  refreshTokenTTLHours: 24h
storage:
  bucketName: aggregator
